# Generated by Django 4.2.18 on 2025-02-15 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front", models.CharField(max_length=100)),
                ("back", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ColumnCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("value", models.PositiveIntegerField()),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.card"
                    ),
                ),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.column"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="column",
            name="cards",
            field=models.ManyToManyField(through="myapp.ColumnCell", to="myapp.card"),
        ),
        migrations.CreateModel(
            name="BoardColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_number", models.PositiveSmallIntegerField()),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.board"
                    ),
                ),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.column"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="board",
            name="columns",
            field=models.ManyToManyField(
                through="myapp.BoardColumn", to="myapp.column"
            ),
        ),
        migrations.AddConstraint(
            model_name="columncell",
            constraint=models.UniqueConstraint(
                fields=("column", "row_number"), name="unique_column_card"
            ),
        ),
        migrations.AddConstraint(
            model_name="boardcolumn",
            constraint=models.UniqueConstraint(
                fields=("board", "column_number"), name="unique_board_column"
            ),
        ),
    ]
